---
# Source: child-apps-in-other-namespaces/templates/child-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: cicd-gitops-devtest
spec:
  destination:
    namespace: cicd-gitops-devtest
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/AD/cicd-exemplar-pipeline-manifests
    targetRevision: main
    path: applications
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
